name: Azure Federated Credentials login
description: Login to Azure Powershell with Federated Credentials, also installs Az.Accounts if it is not installed
inputs:
  client-id:
    required: true
    description: Client ID of the identity to federate
  tenant-id:
    required: true
    description: Tenant ID of the identity to federate
  enable-cli:
    required: false
    description: Use with Azure CLI
runs:
  using: "composite"
  steps:
    - name: Login
      env:
        CLIENT_ID: ${{ inputs.client-id }}
        TENANT_ID: ${{ inputs.tenant-id }}
        ENABLE_CLI: ${{ inputs.enable-cli }}
      shell: pwsh
      run: |
        # Install Az.Accounts if not available
        if(-not (Get-Module Az.Accounts -ListAvailable)){
          Install-Module Az.Accounts -Force -ErrorAction Stop
        }

        # Get federated token
        $secureOIDCToken = $ENV:ACTIONS_ID_TOKEN_REQUEST_TOKEN | ConvertTo-SecureString -AsPlainText
        $federatedToken = (Invoke-RestMethod "$($ENV:ACTIONS_ID_TOKEN_REQUEST_URL)&audience=api://AzureADTokenExchange" -Authentication Bearer -token $secureOIDCToken).value

        # Connect to Azure account
        Connect-AzAccount -FederatedToken $federatedToken -Tenant $Env:TENANT_ID -ApplicationID $Env:CLIENT_ID -ErrorAction Stop

        # Az Login if enable-cli option is set
        if($ENV:ENABLE_CLI) {
          az login --service-principal -u $($Env:CLIENT_ID) -t $($Env:TENANT_ID) --federated-token $federatedToken --allow-no-subscriptions
        }
